name: daily-crawl

on:
  schedule:
     - cron: '*/5 * * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.x
      - name: Install Python dependencies
        run: python -m pip install --upgrade pip pandas
      - name: Run craw code
        run:
          python get_shop_info.py
          git config user.name Phạm Trần Gia Phú
          git config user.email giaphupham196@gmail.com
          git add .
          git commit -m "crongenerated"
          git push
