name: daily-crawl

on:
  schedule:
     - cron: '*/5 * * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.x
      - name: Install Python dependencies
        run: python -m pip install --upgrade pip pandas
      - name: Run crawl code
        run: |
          git config user.name @giaphupham
          git config user.email giaphupham196@gmail.com
          git add .
          git commit -m "Add new file"
          git push